### ISSUE TITLE
Error when building skulpt

### ISSUE THREAD

**Issue by LucianBuzzo** [blockpy-edu/blockpy#114]
Hi, I followed the installation instructions, but when running `npm run devbuild` for the skulpt package, I encounter the following error:
```
Error: Cannot find module '../../dist/skulpt.js'
Require stack:
- /home/lucian/projects/blockpy-robot/blockpy-edu/skulpt/support/run/require-skulpt.js
- /home/lucian/projects/blockpy-robot/blockpy-edu/skulpt/support/build/wrapmodules.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at requireSkulpt (/home/lucian/projects/blockpy-robot/blockpy-edu/skulpt/support/run/require-skulpt.js:16:30)
    at Object.<anonymous> (/home/lucian/projects/blockpy-robot/blockpy-edu/skulpt/support/build/wrapmodules.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/lucian/projects/blockpy-robot/blockpy-edu/skulpt/support/run/require-skulpt.js',
    '/home/lucian/projects/blockpy-robot/blockpy-edu/skulpt/support/build/wrapmodules.js'
  ]
}
No skulpt distribution, run 'npm run build' or 'npm run devbuild' first.
```

It appears that building skulpt requires a build skulpt package.

Any help on this issue would be appreciated!

**Comment by LucianBuzzo** [comment]
I downloaded the built skulpt code from https://think.cs.vt.edu/blockpy/static/gen/skulpt.js and added it as `dist/skulpt.js`, which seems to have let me continue with the installation steps.

**Comment by mairasamary** [comment]
I am seeing the same issue. The documentation doesn't mention the exact version of npm to use. Maybe the issue is related to the fact that I am using the latest version of npm while the software needs to be built with an older one? Please advise.
